Make authorization_jwt writable
versatica/JsSIP pull request #676
Opened 2020-12-14 14:16 UTC by fabrykowski

Allows to set the `authorization_jwt` in the UA-config during runtime.
This is necessary for short-lived JWTs.

2020-12-14 14:36 UTC, ibc requested changes

2020-12-14 14:36 UTC, ibc commented on lib/UA.js
> +
Please move it at the end since I don't think this is more relevant than the other password related fields.

2020-12-14 14:36 UTC, ibc commented on lib/UA.js
> +      }
Same here, move it after 'ha1'.

2020-12-14 14:36 UTC, ibc commented on lib/UA.js
> +      'authorization_jwt', 'authorization_user', 'password', 'realm', 'ha1', 'display_name', 'register'
Same, move after 'ha1'.

2020-12-14 14:36 UTC, ibc commented on lib/UA.js
> +          case 'authorization_jwt':
Same

2020-12-14 14:47 UTC, ibc approved these changes
LGTM. Can you please also create a PR for the documentation site?

@jmillan any thoughts?

2020-12-14 15:31 UTC, fabrykowski commented
versatica/jssip.net#7

2020-12-14 15:47 UTC, tzackrisson commented
Unsubscribe

> On 14 Dec 2020, at 16:31, Lukas Fabrykowski <notifications@github.com> wrote:
> 
> ﻿
> versatica/jssip.net#7
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-14 15:51 UTC, jmillan commented
LGTM

2020-12-14 16:11 UTC, ibc requested changes

2020-12-14 16:11 UTC, ibc commented on lib/Config.js
> +  authorization_jwt  : null,
Please move this as well after 'ha1'.

2020-12-14 17:00 UTC, fabrykowski commented on lib/Config.js
> +  authorization_jwt  : null,
Sorry – I've forgotten that one...

2020-12-15 12:35 UTC, ibc approved these changes

2020-12-15 12:37 UTC, ibc reviewed
@jmillan does this PR require changes in TypeScript definitions in `UA.d.ts`?

2020-12-15 12:39 UTC, fabrykowski commented
No, versatica/JsSIP#675 already added `authorization_jwt` to the type definitions.

2020-12-15 12:42 UTC, merged

2020-12-15 12:46 UTC, ibc commented
jssip 3.6.3 released. Thanks.