Enable custom From-Header for outbound calls
versatica/JsSIP pull request #677
Opened 2020-12-14 14:17 UTC by fabrykowski

Enables setting a From-header different from the Contact-header for an outbound call.

2020-12-14 14:31 UTC, fabrykowski commented
I'm willing to prepare the updated documentation as well, but I don't know where.

2020-12-14 14:34 UTC, ibc commented
What is the motivation for this?

2020-12-14 14:53 UTC, fabrykowski commented
For example multiple people working in an office with a central reception number. (e.g. support hotline)
All desk phones and VoIP-PSTN-carriers ignore the `display_name`-part of the From-header and display the username instead. So I need a way to send `From: <sip:+1234567890@example.com>;tag=xyz` in the INVITEs, despite REGISTERing as `From: <sip:desk-phone-123@example.com>;tag=abc`.

2020-12-14 14:57 UTC, ibc commented
For that, the `P-Preferred-Identity` header must be used as stated by the RFC:

- https://tools.ietf.org/html/rfc3325#section-9.2
- https://tools.ietf.org/html/rfc5876

Sending a random/unknown `From` header is not the way to go.

2020-12-14 15:18 UTC, fabrykowski commented
Unfortunately RFC 3325 is only a memo ("This memo provides information for the Internet community.  It does not specify an Internet standard of any kind.") and the PBXs in question only support the official RFC 3261 with the corresponding From-header ([8.1.1.3](https://tools.ietf.org/html/rfc3261#section-8.1.1.3) and [20.20](https://tools.ietf.org/html/rfc3261#section-20.20)).

2020-12-14 16:18 UTC, ibc commented
@jmillan thoughts?

2020-12-14 16:19 UTC, ibc commented
> Besides: if `anonymous` is set, it does exactly the same.

This is how anonymous call must be done according to the RFCs.

2020-12-14 16:20 UTC, ibc requested changes

2020-12-14 16:20 UTC, ibc commented on lib/RTCSession.js
> +        requestParams.from_uri = URI.parse(options.from_uri);
`P-Preferred-Identity` is required if URI in From header does not honor the original one.

```suggestion
        requestParams.from_uri = URI.parse(options.from_uri);
        extraHeaders.push(`P-Preferred-Identity: ${this._ua.configuration.uri.toString()}`);
```

2020-12-14 20:47 UTC, fabrykowski commented
My precise use case:
I am developing a software for front-office employees, who call customers on behalf of other back-office employees. If the customer could not be reached, they should be able to call back the correct back-office employee.
I have run a test with three different PSTN endpoints and all of them ignored the contents of `P-Preferred-Identity`, while displaying the value from the `From` header.

2020-12-15 08:55 UTC, jmillan commented
Hi @fabrykowski, I see your scenario and concern. Here some changes to your proposal.

* Use `options.fromUserName` as **string** instead of providing a hole URI. We don't want to change the URI host.
* Slight code cleanup.

```js
    if (anonymous)
    {
      requestParams.from_display_name = 'Anonymous';
      requestParams.from_uri = new URI('sip', 'anonymous', 'anonymous.invalid');

      extraHeaders.push(`P-Preferred-Identity: ${this._ua.configuration.uri.toString()}`);
      extraHeaders.push('Privacy: id');
    }
    else if (options.fromUserName)
    {
      requestParams.from_uri = new URI('sip', options.fromUserName, this._ua.configuration.uri.host);

      extraHeaders.push(`P-Preferred-Identity: ${this._ua.configuration.uri.toString()}`);
    }

    if (options.fromDisplayName)
    {
      requestParams.from_display_name = options.fromDisplayName;
    }

```

2020-12-15 09:28 UTC, fabrykowski commented
I like the idea of `options.fromUserName`!

The standalone `if`-block for `fromDisplayName` allows to override the display name even if `anonymous` is set – I like this, because then the name can be localised.

2020-12-15 12:39 UTC, ibc approved these changes
I approve this, but it must first added to the doc website. Can you please do a PR also in there?

2020-12-15 12:40 UTC, fabrykowski commented
See versatica/jssip.net#8

2020-12-17 10:26 UTC, merged

2020-12-17 10:33 UTC, fabrykowski commented
Thanks!

2020-12-17 10:57 UTC, jmillan commented
New version released, thanks @fabrykowski!